version: '3.8'

services:
  video-reducer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: video-reducer
    working_dir: /app
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./app:/app
    ports:
      - 3030:3030
    environment:
      - NODE_ENV=development
    devices:
     - /dev/rga:/dev/rga
     - /dev/dri:/dev/dri
     - /dev/dma_heap:/dev/dma_heap
     - /dev/mpp_service:/dev/mpp_service
     - /dev/rk_cec:/dev/rk_cec  
    networks:
      docker:
    logging:
      options:
        max-size: 100M

networks:
  docker:
    external: true